#!/bin/bash

#clear screen
clear

# Comment about first script in bash wooo
echo "Hello World!"

#It worked, before I even gave the file name for the script it interpreted it from the first line I guess.
#Let's work on some variables now

creatorName="Josh Hale"
#Weird variables have to be defined with no whitespace around =

#without "" is fine too
echo "$creatorName"
echo "Created this program"

echo ${creatorName/Josh/J.}

#How to find string length
echo ${#creatorName}

myArray=(one two three four five six)

#Around here I started using command mode in vim to delete then (p)aste copies on new lines
echo $myArray

#Print any element in whatever index
echo ${myArray[0]}

#Print all elements
echo ${myArray[@]}

#Number of elements
echo ${#myArray[@]}

#Prints fourth element onward
echo ${myArray[@]:3}

#Prints 3 elements starting from the second
echo ${myArray[@]:1:3}


#Print all elements on a new line
for i in "${myArray[@]}"; do
	echo "$i"
done
#interesting use of indentation, need semicolor after loop declaration then everything could work one line

echo {1..20}
echo {a..z}

#Executes pwd
echo "This program is in $(pwd)"

echo "What's your name?"
read Name #Doesn't need to be saved to variable, can be echoed in read
echo Hello, $Name!


