Playground.class: Playground.java Pet.class Chameleon.class MoleRat.class Hunger.class Excitement.class Wrinkliness.class Attribute.class
	javac Playground.java

Pet.class: Pet.java
	javac Pet.java

Chameleon.class: Chameleon.java
	javac Chameleon.java

MoleRat.class: MoleRat.java
	javac MoleRat.java

Hunger.class: Hunger.java
	javac Hunger.java

Excitement.class: Excitement.java
	javac Excitement.java

Wrinkliness.class: Wrinkliness.java
	javac Wrinkliness.java

Attribute.class: Attribute.java
	javac Attribute.java

run: Playground.class
	java Playground

clean:
	rm *.class
